### ISSUE TITLE
Custom MAC adress

### ISSUE THREAD

**Issue by Cadybara** [gjroots/esp32_nat_router_plus#23] opened 2024-04-07 13:58 UTC
When I try to use a custom MAC Adress for the ESP (I guess it should be possible to do that) I can't acess the input box because something always adds a `pointer-event:none` to the box and I can not find where this comes from.
If it was planned that you can change the MAC to a custom value this could be a bug if it was not a planned feature see this issue as a feature request.

**Comment by gjroots** [comment] 2024-04-07 14:53
Hi @Cadybara,

It's not a bug. The custom Mac address feature was intentionally removed for some reason. It will be needed and released in the next update.

**Comment by Cadybara** [comment] 2024-04-07 15:04
okay thanks for the fast answer and this usefull repo

**Closed** 2024-04-07 15:05 UTC
